name: Cask Test Action

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'action.yml', 'main.rb' ]
  pull_request:
    branches: [ main ]
    paths: [ 'action.yml', 'main.rb' ]

jobs:
  test-livecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Test livecheck with dry-run
        uses: ./ # Use this action from the current repo
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          tap: laniksj/homebrew-tap
          cask: android-messages-plus
          livecheck: true
          dryrun: true
  test-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Test bump with dry-run
        uses: ./ # Use this action from the current repo
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          tap: laniksj/homebrew-tap
          cask: android-messages-plus
          livecheck: true
          dryrun: true
